### PR TITLE
 URL routing support

### PR DESCRIPTION
**Pull request by jnbooth**
Addresses #72. When the page is loaded, it reads its initial state from URL parameters. It then updates those parameters in browser history whenever its state changes.

### CODE REVIEW

**Comment by wavebeem** [comment]
This looks great, thanks!

One thing that's missing is a redirect from `/`. If you click the Netlify deploy preview you'll see that going to `/` doesn't redirect you to `/offense`, leaving you at a blank screen.

This one is a minor detail, but I noticed the URL flickers when changing tabs.

`/offense?types=fire` -> `/defense` -> `/defense?types=normal`

Like you very briefly see `/defense` before `/defense?types=normal`. Perhaps switching from `React.useEffect` to `React.useLayoutEffect` for routing code would fix it? If not, no worries, I'll still merge it even with the flicker.

Finally, feel free to add yourself to the "Special Thanks" section in the info page! I appreciate the work.

**Comment by jnbooth** [comment]
The flicker happens because tab buttons are simple links, e.g. `href="/defense"`, so the app first navigates to that page and then loads in parameters from its state. I'm a React novice, so maybe there is a better way that I'm missing, but the two ways I can think of addressing that would be:

1. Save each tab's parameters and send them to the navigation buttons. For example, instead of the defense link being `href="/defense"`, it could be `href="/defense?types=normal"`. This seems link unusual behavior for a navigation section.
2. Bring back the `changeTab` system and make the navigation buttons fake with `event.preventDefault()`. In this case, the app no longer uses BrowserRouter.

That's why I went with the flickering option. Like I said, there's a lot I don't know about React, so maybe you see another option.

**Comment by wavebeem** [comment]
That makes sense. No worries then! I can play around with this later and see what I think about flickering and alternatives. Thanks a bunch.

Do you want to be in the credits? The offer is still open if you'd like to add yourself to the Info screen. Let me know either way and then I'll merge this.

**Comment by jnbooth** [comment]
Nah. Just happy to help.

**Pull request merged**
