### PR TITLE
Use URI hash for navigation

### PR DESCRIPTION
**Pull request by jnbooth**
Examples:
pkmn.help/#offense/fighting+ground+fire+psychic
pkmn.help/#defense/fairy+poison
pkmn.help/#pokedex
pkmn.help/#pokedex/3
pkmn.help/#pokedex/saur
pkmn.help/#pokedex/sa/3
pkmn.help/#info

### CODE REVIEW

**Comment by wavebeem** [comment]
Thanks for the PR! I've actually been meaning to add this.

I was planning to do the URLs like this.

```
pkmn.help/offense?types=fighting+ground+fire+psychic
pkmn.help/defense?types=fairy+poison
pkmn.help/pokedex?q=&page=0
pkmn.help/pokedex?q=saur&page=0
pkmn.help/pokedex?q=sa&page=3
pkmn.help/info
```

I think something like React Router's `BrowserRouter` component would be good for this. And then I was gonna hook into route transitions to send pageview events to Google Analytics.

For the "pretty" URLs the `_redirects` file would need to be updated, and the `devServer` block in `webpack.config.js` would need to be updated as well to serve the index HTML as a fallback file.

If you'd like to work on that, feel free. Otherwise I'll get to it soon. I understand it's quite a bit different in scope than your PR, so no worries if you're not interested.

**Comment by jnbooth** [comment]
Sure, I'll take a stab at that.

**Comment by wavebeem** [comment]
Cool! Feel free to open a PR early if you'd like. It's really easy to check out work in progress with the Netlify PR deploy job.

**Comment by wavebeem** [comment]
I made https://github.com/wavebeem/pkmn.help/issues/72 to track what I'm looking for out of this feature, plus some thoughts on how to accomplish it.

**Pull request closed without merging**
