### PR TITLE
refactor(footer): Extract footer into it's own component

### PR DESCRIPTION
**Pull request by smoak**
Isolates it so it can be changed/tested easier.

### CODE REVIEW

**Comment by wavebeem** [comment]
Is there another way we can organize this? I would prefer to have `src/Footer.tsx` and the tests and snapshots in another folder if that's possible. I appreciate the PR though.

**Comment by smoak** [comment]
It sounds like you want all components to live in `src`? The trouble with having all components in `src` as top-level files is that you end up with a ton of files in one directory. Separating things out into folders allows you to break out a component into sub components. It's not a terribly strong opinion (and it's your project after all). I can move `Footer.tsx` back up into the top-level `src` if you prefer.

It sounds like you want a separate directory for tests too? jest and the community colocate tests and snapshots near the components they are testing. However, I believe it's easy enough to change if you prefer they live somewhere else.

**Comment by wavebeem** [comment]
Yeah, my preference is to have not have folders per component. I'm fine with a bigger src folder personally. And yeah I thought jest had like a `__test__` folder or something that you could use (that's how we have it at work at least)

**Comment by smoak** [comment]
Ok. I'll move it over. I think jest will look for test files anywhere really. Would you prefer `__tests__` inside the `src` dir or up one level outside `src`?

**Comment by wavebeem** [comment]
Yeah that sounds good to me 🙂if you don't mind me being a little nit picky
about it 😂

**Comment by wavebeem** [comment]
Sorry I meant to say also __test__ beside src not inside

**Comment by smoak** [comment]
No worries :) Just updated it.

**Comment by smoak** [comment]
`__tests__` are beside `src` now

**Comment by wavebeem** [comment]
Thank you!

**Pull request merged**
