### PR TITLE
Search preview

### PR DESCRIPTION
**Pull request by DeWolfRobin**
I created the layout for this (please note that the css is pretty fixed and needs to be made responsive)
The problem atm is that I can't find a way to update the active types(please refer to Dex.tsx line 29/30)

### CODE REVIEW

**Comment by wavebeem** [comment]
The hover columns idea is neat, but it's not very phone friendly. Personally I use this more on my phone than anything else, so I wanna make sure it's designed mobile first.

**Comment by DeWolfRobin** [comment]
Got you, I will then create a toggle click when a user clicks the pokemon the defence column will open and when a user clicks a certain type, the offence column will open.

Any hints on how I could set the type of these columns?

**Comment by wavebeem** [comment]
I think getting columns how you want is gonna be pretty hard to have it work across sizes and stick to the top of the viewport. How about the initial idea of just switching tabs automatically? When you go back to the Pokedex you'll still be on the same page and search filter.

**Comment by DeWolfRobin** [comment]
yeah sorry that was what I meant :) I checked out the mobile version and saw there was no place, but changing the tab shouldn't be hard. it's changing the type that may be hard.

**Comment by wavebeem** [comment]
You'll wanna pass these updateType functions from here https://github.com/wavebeem/pkmn.help/blob/master/src/App.tsx#L13-L15 to here https://github.com/wavebeem/pkmn.help/blob/master/src/App.tsx#L52-L58

**Comment by DeWolfRobin** [comment]
I finaly got it :) I will create a new pull request

**Pull request closed without merging**
